src/Entity/Attributes.php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\AttributesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AttributesRepository::class)]
#[ApiResource]
class Attributes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $attribute_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $attribute_group_id = null;

    #[ORM\Column(nullable: true)]
    private ?int $order_sort = null;

    #[ORM\Column(nullable: true)]
    private ?int $type = null;

    #[ORM\Column(nullable: true)]
    private ?bool $active = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $default_value = null;

    #[ORM\Column(type: Types::ARRAY, nullable: true)]
    private ?array $options = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAttributeId(): ?int
    {
        return $this->attribute_id;
    }

    public function setAttributeId(int $attribute_id): static
    {
        $this->attribute_id = $attribute_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getAttributeGroupId(): ?int
    {
        return $this->attribute_group_id;
    }

    public function setAttributeGroupId(?int $attribute_group_id): static
    {
        $this->attribute_group_id = $attribute_group_id;

        return $this;
    }

    public function getOrderSort(): ?int
    {
        return $this->order_sort;
    }

    public function setOrderSort(?int $order_sort): static
    {
        $this->order_sort = $order_sort;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(?int $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): static
    {
        $this->active = $active;

        return $this;
    }

    public function getDefaultValue(): ?string
    {
        return $this->default_value;
    }

    public function setDefaultValue(?string $default_value): static
    {
        $this->default_value = $default_value;

        return $this;
    }

    public function getOptions(): ?array
    {
        return $this->options;
    }

    public function setOptions(?array $options): static
    {
        $this->options = $options;

        return $this;
    }
}

src/Form/AttributesType.php
<?php

namespace App\Form;

use App\Entity\Attributes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AttributesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('attribute_id')
            ->add('name')
            ->add('description')
            ->add('attribute_group_id')
            ->add('order_sort')
            ->add('type')
            ->add('active')
            ->add('default_value')
            ->add('options')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Attributes::class,
        ]);
    }
}

templates/attributes/_delete_form.html.twig
<form method="post" action="{{ path('app_attributes_delete', {'id': attribute.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ attribute.id) }}">
    <button class="btn">Delete</button>
</form>

templates/attributes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/attributes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Attributes{% endblock %}

{% block body %}
    <h1>Edit Attributes</h1>

    {{ include('attributes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_attributes_index') }}">back to list</a>

    {{ include('attributes/_delete_form.html.twig') }}
{% endblock %}

templates/attributes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Attributes index{% endblock %}

{% block body %}
    <h1>Attributes index</h1>

        <label for="attribute">KAMUFLAŻ I KOLOR</label>
        <select name="cars" id="cars">
        {% for attribute in attributes %}
                <option value="name">{{ attribute.name }}</option>
         {% endfor %}
        </select>
        
    

    <a href="{{ path('app_attributes_new') }}">Create new</a>
{% endblock %}

templates/attributes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Attributes{% endblock %}

{% block body %}
    <h1>Create new Attributes</h1>

    {{ include('attributes/_form.html.twig') }}

    <a href="{{ path('app_attributes_index') }}">back to list</a>
{% endblock %}

templates/attributes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Attributes{% endblock %}

{% block body %}
    <h1>Attributes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ attribute.id }}</td>
            </tr>
            <tr>
                <th>Attribute_id</th>
                <td>{{ attribute.attributeId }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ attribute.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ attribute.description }}</td>
            </tr>
            <tr>
                <th>Attribute_group_id</th>
                <td>{{ attribute.attributeGroupId }}</td>
            </tr>
            <tr>
                <th>Order_sort</th>
                <td>{{ attribute.orderSort }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ attribute.type }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ attribute.active ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Default_value</th>
                <td>{{ attribute.defaultValue }}</td>
            </tr>
            <tr>
                <th>Options</th>
                <td>{{ attribute.options }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_attributes_index') }}">back to list</a>

    <a href="{{ path('app_attributes_edit', {'id': attribute.id}) }}">edit</a>

    {{ include('attributes/_delete_form.html.twig') }}
{% endblock %}