src/Entity/ProductStock.php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ProductStockRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductStockRepository::class)]
#[ApiResource]
class ProductStock
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $stock_id = null;

    #[ORM\Column(nullable: true)]
    private ?int $product_id = null;

    #[ORM\Column(nullable: true)]
    private ?float $price = null;

    #[ORM\Column(nullable: true)]
    private ?bool $extended = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $price_type = null;

    #[ORM\Column(nullable: true)]
    private ?bool $active = null;

    #[ORM\Column(nullable: true)]
    private ?bool $default_stock = null;

    #[ORM\Column(nullable: true)]
    private ?float $stock = null;

    #[ORM\Column(type: Types::ARRAY, nullable: true)]
    private ?array $warehouses = null;

    #[ORM\Column(nullable: true)]
    private ?float $warn_level = null;

    #[ORM\Column(nullable: true)]
    private ?float $sold = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $code = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ean = null;

    #[ORM\Column(nullable: true)]
    private ?float $weight = null;

    #[ORM\Column(nullable: true)]
    private ?int $weight_type = null;

    #[ORM\Column(nullable: true)]
    private ?int $availiability_id = null;

    #[ORM\Column(nullable: true)]
    private ?int $delivery_id = null;

    #[ORM\Column(nullable: true)]
    private ?int $gfx_id = null;

    #[ORM\Column(type: Types::ARRAY, nullable: true)]
    private ?array $options = null;

    #[ORM\Column(nullable: true)]
    private ?float $package = null;

    #[ORM\Column(nullable: true)]
    private ?float $price_wholesale = null;

    #[ORM\Column(nullable: true)]
    private ?float $price_special = null;

    #[ORM\Column(nullable: true)]
    private ?int $price_type_wholesale = null;

    #[ORM\Column(nullable: true)]
    private ?int $price_type_special = null;

    #[ORM\Column(nullable: true)]
    private ?float $price_buying = null;

    #[ORM\Column(nullable: true)]
    private ?int $calculation_unit_id = null;

    #[ORM\Column(nullable: true)]
    private ?float $calculation_unit_ratio = null;

    #[ORM\Column(nullable: true)]
    private ?float $historical_lowest_price = null;

    #[ORM\Column(nullable: true)]
    private ?float $wholesale_historical_lowest_price = null;

    #[ORM\Column(nullable: true)]
    private ?float $special_historical_lowest_price = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStockId(): ?int
    {
        return $this->stock_id;
    }

    public function setStockId(int $stock_id): static
    {
        $this->stock_id = $stock_id;

        return $this;
    }

    public function getProductId(): ?int
    {
        return $this->product_id;
    }

    public function setProductId(?int $product_id): static
    {
        $this->product_id = $product_id;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getExtended(): ?bool
    {
        return $this->extended;
    }

    public function setExtended(?bool $extended): static
    {
        $this->extended = $extended;

        return $this;
    }

    public function getPriceType(): ?string
    {
        return $this->price_type;
    }

    public function setPriceType(?string $price_type): static
    {
        $this->price_type = $price_type;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): static
    {
        $this->active = $active;

        return $this;
    }

    public function isDefaultStock(): ?bool
    {
        return $this->default_stock;
    }

    public function setDefaultStock(?bool $default_stock): static
    {
        $this->default_stock = $default_stock;

        return $this;
    }

    public function getStock(): ?float
    {
        return $this->stock;
    }

    public function setStock(?float $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getWarehouses(): ?array
    {
        return $this->warehouses;
    }

    public function setWarehouses(?array $warehouses): static
    {
        $this->warehouses = $warehouses;

        return $this;
    }

    public function getWarnLevel(): ?float
    {
        return $this->warn_level;
    }

    public function setWarnLevel(?float $warn_level): static
    {
        $this->warn_level = $warn_level;

        return $this;
    }

    public function getSold(): ?float
    {
        return $this->sold;
    }

    public function setSold(?float $sold): static
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getEan(): ?string
    {
        return $this->ean;
    }

    public function setEan(?string $ean): static
    {
        $this->ean = $ean;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): static
    {
        $this->weight = $weight;

        return $this;
    }

    public function getWeightType(): ?int
    {
        return $this->weight_type;
    }

    public function setWeightType(?int $weight_type): static
    {
        $this->weight_type = $weight_type;

        return $this;
    }

    public function getAvailiabilityId(): ?int
    {
        return $this->availiability_id;
    }

    public function setAvailiabilityId(?int $availiability_id): static
    {
        $this->availiability_id = $availiability_id;

        return $this;
    }

    public function getDeliveryId(): ?int
    {
        return $this->delivery_id;
    }

    public function setDeliveryId(?int $delivery_id): static
    {
        $this->delivery_id = $delivery_id;

        return $this;
    }

    public function getGfxId(): ?int
    {
        return $this->gfx_id;
    }

    public function setGfxId(?int $gfx_id): static
    {
        $this->gfx_id = $gfx_id;

        return $this;
    }

    public function getOptions(): ?array
    {
        return $this->options;
    }

    public function setOptions(?array $options): static
    {
        $this->options = $options;

        return $this;
    }

    public function getPackage(): ?float
    {
        return $this->package;
    }

    public function setPackage(?float $package): static
    {
        $this->package = $package;

        return $this;
    }

    public function getPriceWholesale(): ?float
    {
        return $this->price_wholesale;
    }

    public function setPriceWholesale(float $price_wholesale): static
    {
        $this->price_wholesale = $price_wholesale;

        return $this;
    }

    public function getPriceSpecial(): ?float
    {
        return $this->price_special;
    }

    public function setPriceSpecial(?float $price_special): static
    {
        $this->price_special = $price_special;

        return $this;
    }

    public function getPriceTypeWholesale(): ?int
    {
        return $this->price_type_wholesale;
    }

    public function setPriceTypeWholesale(?int $price_type_wholesale): static
    {
        $this->price_type_wholesale = $price_type_wholesale;

        return $this;
    }

    public function getPriceTypeSpecial(): ?int
    {
        return $this->price_type_special;
    }

    public function setPriceTypeSpecial(?int $price_type_special): static
    {
        $this->price_type_special = $price_type_special;

        return $this;
    }

    public function getPriceBuying(): ?float
    {
        return $this->price_buying;
    }

    public function setPriceBuying(?float $price_buying): static
    {
        $this->price_buying = $price_buying;

        return $this;
    }

    public function getCalculationUnitId(): ?int
    {
        return $this->calculation_unit_id;
    }

    public function setCalculationUnitId(?int $calculation_unit_id): static
    {
        $this->calculation_unit_id = $calculation_unit_id;

        return $this;
    }

    public function getCalculationUnitRatio(): ?float
    {
        return $this->calculation_unit_ratio;
    }

    public function setCalculationUnitRatio(?float $calculation_unit_ratio): static
    {
        $this->calculation_unit_ratio = $calculation_unit_ratio;

        return $this;
    }

    public function getHistoricalLowestPrice(): ?float
    {
        return $this->historical_lowest_price;
    }

    public function setHistoricalLowestPrice(?float $historical_lowest_price): static
    {
        $this->historical_lowest_price = $historical_lowest_price;

        return $this;
    }

    public function getWholesaleHistoricalLowestPrice(): ?float
    {
        return $this->wholesale_historical_lowest_price;
    }

    public function setWholesaleHistoricalLowestPrice(?float $wholesale_historical_lowest_price): static
    {
        $this->wholesale_historical_lowest_price = $wholesale_historical_lowest_price;

        return $this;
    }

    public function getSpecialHistoricalLowestPrice(): ?float
    {
        return $this->special_historical_lowest_price;
    }

src/Form/ProductStockType.php
<?php

namespace App\Form;

use App\Entity\ProductStock;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductStockType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('stock_id')
            ->add('product_id')
            ->add('price')
            ->add('extended')
            ->add('price_type')
            ->add('active')
            ->add('default_stock')
            ->add('stock')
            ->add('warehouses')
            ->add('warn_level')
            ->add('sold')
            ->add('code')
            ->add('ean')
            ->add('weight')
            ->add('weight_type')
            ->add('availiability_id')
            ->add('delivery_id')
            ->add('gfx_id')
            ->add('options')
            ->add('package')
            ->add('price_wholesale')
            ->add('price_special')
            ->add('price_type_wholesale')
            ->add('price_type_special')
            ->add('price_buying')
            ->add('calculation_unit_id')
            ->add('calculation_unit_ratio')
            ->add('historical_lowest_price')
            ->add('wholesale_historical_lowest_price')
            ->add('special_historical_lowest_price')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ProductStock::class,
        ]);
    }
}

src/Controller/ProductStockController.php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Controller;

use App\Entity\ProductStock;
use App\Form\ProductStockType;
use App\Repository\ProductStockRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Controller\ApiController;
use Psr\Log\LoggerInterface;

#[Route('/product/stock')]
class ProductStockController extends AbstractController
{
    #[Route('/', name: 'app_product_stock_index', methods: ['GET'])]
    public function index(ProductStockRepository $productStockRepository): Response
    {
        return $this->render('product_stock/index.html.twig', [
            'product_stocks' => $productStockRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_product_stock_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $productStock = new ProductStock();
        $form = $this->createForm(ProductStockType::class, $productStock);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($productStock);
            $entityManager->flush();

            return $this->redirectToRoute('app_product_stock_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product_stock/new.html.twig', [
            'product_stock' => $productStock,
            'form' => $form,
        ]);
    }

    #[Route('/{stock_id}', name: 'app_product_stock_show', methods: ['GET'])]
    public function show(ProductStock $productStock): Response
    {
        return $this->render('product_stock/show.html.twig', [
            'product_stock' => $productStock,
        ]);
    }

    #[Route('/{stock_id}/edit', name: 'app_product_stock_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ProductStock $productStock, EntityManagerInterface $entityManager, ApiController $api, LoggerInterface $logger): Response
    {
        $id = $productStock->getStockId();
        $form = $this->createForm(ProductStockType::class, $productStock);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $endpoint = 'product-stocks/';
            $data_shoper = [
                'price' => $form['price']->getData(),
                'price_type' => $form['price_type']->getData(),
                'active' => $form['active']->getData(),
                'default' => $form['default_stock']->getData(),
                'stock' => $form['stock']->getData(),
                'warehouses' => $form['warehouses']->getData(),
                'warn_level'=> $form['warn_level']->getData(),
                'sold'=> $form['sold']->getData(),
                'code'=> $form['code']->getData(),
                'ean'=> $form['ean']->getData(),
                'weight'=> $form['weight_type']->getData(),
                'weight_type'=> $form['weight_type']->getData(),
                'availiability_id'=> $form['availiability_id']->getData(),
                'delivery_id'=> $form['delivery_id']->getData(),
                'gfx_id' => $form['gfx_id']->getData(),
                'options' => $form['options']->getData(),
                'package'=> $form['package']->getData(),
                'price_wholesale'=> $form['price_wholesale']->getData(),
                'price_special'=> $form['price_special']->getData(),
                'price_type_wholesale'=> $form['price_type_wholesale']->getData(),
                'price_type_special'=> $form['price_type_special']->getData(),
                'price_buying'=> $form['price_buying']->getData(),
                'calculation_unit_id' => $form['calculation_unit_id']->getData(),
                'calculation_unit_ratio'=> $form['calculation_unit_ratio']->getData(),
                'historical_lowest_price' => $form['historical_lowest_price']->getData(),
                'wholesale_historical_lowest_price' => $form['wholesale_historical_lowest_price']->getData(),
                'special_historical_lowest_price' => $form['special_historical_lowest_price']->getData(),  
            ];
            $logger->info(json_encode($api->put_shoper($endpoint, $id, $data_shoper)));

            $entityManager->flush(); 
            return $this->redirectToRoute('app_product_stock_edit', ['stock_id' => $id], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product_stock/edit.html.twig', [
            'product_stock' => $productStock,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_product_stock_delete', methods: ['POST'])]
    public function delete(Request $request, ProductStock $productStock, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$productStock->getId(), $request->request->get('_token'))) {
            $entityManager->remove($productStock);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_product_stock_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/product_stock/_delete_form.html.twig
<form method="post" action="{{ path('app_product_stock_delete', {'id': product_stock.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product_stock.id) }}">
    <button class="btn">Delete</button>
</form>

templates/product_stock/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/product_stock/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ProductStock{% endblock %}

{% block body %}
    <h1>Edit ProductStock</h1>

    {{ include('product_stock/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_product_stock_index') }}">back to list</a>

    {{ include('product_stock/_delete_form.html.twig') }}
{% endblock %}

templates/product_stock/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProductStock index{% endblock %}

{% block body %}
    <h1>ProductStock index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Stock_id</th>
                <th>Product_id</th>
                <th>Price</th>
                <th>Extended</th>
                <th>Price_type</th>
                <th>Active</th>
                <th>Default_stock</th>
                <th>Stock</th>
                <th>Warehouses</th>
                <th>Warn_level</th>
                <th>Sold</th>
                <th>Code</th>
                <th>Ean</th>
                <th>Weight</th>
                <th>Weight_type</th>
                <th>Availiability_id</th>
                <th>Delivery_id</th>
                <th>Gfx_id</th>
                <th>Options</th>
                <th>Package</th>
                <th>Price_wholesale</th>
                <th>Price_special</th>
                <th>Price_type_wholesale</th>
                <th>Price_type_special</th>
                <th>Price_buying</th>
                <th>Calculation_unit_id</th>
                <th>Calculation_unit_ratio</th>
                <th>Historical_lowest_price</th>
                <th>Wholesale_historical_lowest_price</th>
                <th>Special_historical_lowest_price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product_stock in product_stocks %}
            <tr>
                <td>{{ product_stock.id }}</td>
                <td>{{ product_stock.stockId }}</td>
                <td>{{ product_stock.productId }}</td>
                <td>{{ product_stock.price }}</td>
                <td>{{ product_stock.extended ? 'Yes' : 'No' }}</td>
                <td>{{ product_stock.priceType }}</td>
                <td>{{ product_stock.active ? 'Yes' : 'No' }}</td>
                <td>{{ product_stock.defaultStock ? 'Yes' : 'No' }}</td>
                <td>{{ product_stock.stock }}</td>
                <td>{{ product_stock.warehouses ? product_stock.warehouses|join(', ') : '' }}</td>
                <td>{{ product_stock.warnLevel }}</td>
                <td>{{ product_stock.sold }}</td>
                <td>{{ product_stock.code }}</td>
                <td>{{ product_stock.ean }}</td>
                <td>{{ product_stock.weight }}</td>
                <td>{{ product_stock.weightType }}</td>
                <td>{{ product_stock.availiabilityId }}</td>
                <td>{{ product_stock.deliveryId }}</td>
                <td>{{ product_stock.gfxId }}</td>
                <td>{{ product_stock.options ? product_stock.options|join(', ') : '' }}</td>
                <td>{{ product_stock.package }}</td>
                <td>{{ product_stock.priceWholesale }}</td>
                <td>{{ product_stock.priceSpecial }}</td>
                <td>{{ product_stock.priceTypeWholesale }}</td>
                <td>{{ product_stock.priceTypeSpecial }}</td>
                <td>{{ product_stock.priceBuying }}</td>
                <td>{{ product_stock.calculationUnitId }}</td>
                <td>{{ product_stock.calculationUnitRatio }}</td>
                <td>{{ product_stock.historicalLowestPrice }}</td>
                <td>{{ product_stock.wholesaleHistoricalLowestPrice }}</td>
                <td>{{ product_stock.specialHistoricalLowestPrice }}</td>
                <td>
                    <a href="{{ path('app_product_stock_show', {'stock_id': product_stock.stockId}) }}">show</a>
                    <a href="{{ path('app_product_stock_edit', {'stock_id': product_stock.stockId}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="32">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_product_stock_new') }}">Create new</a>
{% endblock %}

templates/product_stock/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nowy wariant{% endblock %}

{# <button type="button" class="btn btn-default btn-lg btn-block" data-toggle="modal" data-target="#sourceCodeModal">
      <i class="fa fa-cogs" aria-hidden="true"></i> {{ 'action.app_product_stock_new'|trans }}
</button> #}

{% block body %}
    <h1>Dodaj nowy wariant</h1>
    <div class=""></div>
    {{ include('product_stock/_form.html.twig') }}                   
    <a href="{{ path('app_product_stock_index') }}">back to list</a>
{% endblock %}

templates/product_stock/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProductStock{% endblock %}

{% block body %}
    <h1>ProductStock</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product_stock.id }}</td>
            </tr>
            <tr>
                <th>Stock_id</th>
                <td>{{ product_stock.stockId }}</td>
            </tr>
            <tr>
                <th>Product_id</th>
                <td>{{ product_stock.productId }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ product_stock.price }}</td>
            </tr>
            <tr>
                <th>Extended</th>
                <td>{{ product_stock.extended ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Price_type</th>
                <td>{{ product_stock.priceType }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ product_stock.active ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Default_stock</th>
                <td>{{ product_stock.defaultStock ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ product_stock.stock }}</td>
            </tr>
            <tr>
                <th>Warehouses</th>
                <td>{{ product_stock.warehouses ? product_stock.warehouses|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Warn_level</th>
                <td>{{ product_stock.warnLevel }}</td>
            </tr>
            <tr>
                <th>Sold</th>
                <td>{{ product_stock.sold }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ product_stock.code }}</td>
            </tr>
            <tr>
                <th>Ean</th>
                <td>{{ product_stock.ean }}</td>
            </tr>
            <tr>
                <th>Weight</th>
                <td>{{ product_stock.weight }}</td>
            </tr>
            <tr>
                <th>Weight_type</th>
                <td>{{ product_stock.weightType }}</td>
            </tr>
            <tr>
                <th>Availiability_id</th>
                <td>{{ product_stock.availiabilityId }}</td>
            </tr>
            <tr>
                <th>Delivery_id</th>
                <td>{{ product_stock.deliveryId }}</td>
            </tr>
            <tr>
                <th>Gfx_id</th>
                <td>{{ product_stock.gfxId }}</td>
            </tr>
            <tr>
                <th>Options</th>
                <td>{{ product_stock.options ? product_stock.options|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Package</th>
                <td>{{ product_stock.package }}</td>
            </tr>
            <tr>
                <th>Price_wholesale</th>
                <td>{{ product_stock.priceWholesale }}</td>
            </tr>
            <tr>
                <th>Price_special</th>
                <td>{{ product_stock.priceSpecial }}</td>
            </tr>
            <tr>
                <th>Price_type_wholesale</th>
                <td>{{ product_stock.priceTypeWholesale }}</td>
            </tr>
            <tr>
                <th>Price_type_special</th>
                <td>{{ product_stock.priceTypeSpecial }}</td>
            </tr>
            <tr>
                <th>Price_buying</th>
                <td>{{ product_stock.priceBuying }}</td>
            </tr>
            <tr>
                <th>Calculation_unit_id</th>
                <td>{{ product_stock.calculationUnitId }}</td>
            </tr>
            <tr>
                <th>Calculation_unit_ratio</th>
                <td>{{ product_stock.calculationUnitRatio }}</td>
            </tr>
            <tr>
                <th>Historical_lowest_price</th>
                <td>{{ product_stock.historicalLowestPrice }}</td>
            </tr>
            <tr>
                <th>Wholesale_historical_lowest_price</th>
                <td>{{ product_stock.wholesaleHistoricalLowestPrice }}</td>
            </tr>
            <tr>
                <th>Special_historical_lowest_price</th>
                <td>{{ product_stock.specialHistoricalLowestPrice }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_product_stock_index') }}">back to list</a>

    <a href="{{ path('app_product_stock_edit', {'id': product_stock.id}) }}">edit</a>

    {{ include('product_stock/_delete_form.html.twig') }}
{% endblock %}