src/Entity/CategoriesTree.php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\CategoriesTreeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\Migrations\Configuration\Migration\JsonFile;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoriesTreeRepository::class)]
#[ApiResource]
class CategoriesTree
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $tree_id = null;

    #[ORM\Column(type: Types::ARRAY, nullable: true)]
    private ?array $children = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTreeId(): ?int
    {
        return $this->tree_id;
    }

    public function setTreeId(int $tree_id): static
    {
        $this->tree_id = $tree_id;

        return $this;
    }

    public function getChildren(): ?array
    {
        return $this->children;
    }

    public function setChildren(?array $children): static
    {
        $this->children = $children;

        return $this;
    }
}

src/Form/CategoriesTreeType.php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form;

use App\Entity\CategoriesTree;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\EntityManagerInterface;

class CategoriesTreeType extends AbstractType
{
    private $em;
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $sampleArray = array(
            'name' => 'John Doe',
            'age' => 30,
            'email' => 'john@example.com',
            'is_active' => true,
            'address' => array(
                'street' => '123 Main Street',
                'city' => 'Anytown',
                'country' => 'USA'
            ),
            'friends' => array(
                'Alice',
                'Bob',
                'Charlie'
            )
        );
        

        // foreach($tree as $item) {
        //     if ($item->getChildren() != null) {
        //         foreach($item->getChildren() as $item) {
        //             $id_children = $item['children'];
        //             print_r($id_children);
        //             // $id_children = $id_children['id'];
        //             $array_tree[$item['id']][$id_children] = $item['id'];
        //         }
        //     } else {
        //         $array_tree[$item->getId()] = null;
        //     }
        // }
        $builder
            ->add('tree_id')
            ->add('children', ChoiceType::class, [
                'choices' => 'cos', 
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CategoriesTree::class,
        ]);
    }
}

src/Controller/CategoriesTreeController.php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Controller;

use App\Entity\CategoriesTree;
use App\Form\CategoriesTree2Type;
use App\Repository\CategoriesTreeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/categories/tree')]
class CategoriesTreeController extends AbstractController
{
    #[Route('/', name: 'app_categories_tree_index', methods: ['GET'])]
    public function index(CategoriesTreeRepository $categoriesTreeRepository): Response
    {
        return $this->render('categories_tree/index.html.twig', [
            'categories_trees' => $categoriesTreeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_categories_tree_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $categoriesTree = new CategoriesTree();
        $form = $this->createForm(CategoriesTree2Type::class, $categoriesTree);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($categoriesTree);
            $entityManager->flush();

            return $this->redirectToRoute('app_categories_tree_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('categories_tree/new.html.twig', [
            'categories_tree' => $categoriesTree,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_categories_tree_show', methods: ['GET'])]
    public function show(CategoriesTree $categoriesTree): Response
    {
        return $this->render('categories_tree/show.html.twig', [
            'categories_tree' => $categoriesTree,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_categories_tree_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CategoriesTree $categoriesTree, EntityManagerInterface $entityManager): Response
    {       
        $categoriesTreeAll = $entityManager->getRepository(CategoriesTree::class)->findAll();
        $form = $this->createForm(CategoriesTree2Type::class, $categoriesTree, [
            'categories_all' => $categoriesTreeAll,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_categories_tree_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('categories_tree/edit.html.twig', [
            'categories_tree' => $categoriesTree,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_categories_tree_delete', methods: ['POST'])]
    public function delete(Request $request, CategoriesTree $categoriesTree, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$categoriesTree->getId(), $request->request->get('_token'))) {
            $entityManager->remove($categoriesTree);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_categories_tree_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/categories_tree/_delete_form.html.twig
<form method="post" action="{{ path('app_categories_tree_delete', {'id': categories_tree.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ categories_tree.id) }}">
    <button class="btn">Delete</button>
</form>

templates/categories_tree/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/categories_tree/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CategoriesTree{% endblock %}

{% block body %}
    <h1>Edit CategoriesTree</h1>

    {{ include('categories_tree/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_categories_tree_index') }}">back to list</a>

    {{ include('categories_tree/_delete_form.html.twig') }}
{% endblock %}

templates/categories_tree/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CategoriesTree index{% endblock %}

{% block body %}
    <h1>CategoriesTree index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Tree_id</th>
                <th>Children</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {# {% for categories_tree in categories_trees %}
            <tr>
                <td>{{ categories_tree.id }}</td>
                <td>{{ categories_tree.treeId }}</td>
                <td>{{ categories_tree.children ? categories_tree.children|join(', ') : '' }}</td>
                <td>
                    <a href="{{ path('app_categories_tree_show', {'id': categories_tree.id}) }}">show</a>
                    <a href="{{ path('app_categories_tree_edit', {'id': categories_tree.id}) }}">edit</a>
                </td>
            </tr>
        {% else %} #}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_categories_tree_new') }}">Create new</a>
{% endblock %}

templates/categories_tree/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CategoriesTree{% endblock %}

{% block body %}
    <h1>Create new CategoriesTree</h1>

    {{ include('categories_tree/_form.html.twig') }}

    <a href="{{ path('app_categories_tree_index') }}">back to list</a>
{% endblock %}

templates/categories_tree/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CategoriesTree{% endblock %}

{% block body %}
    <h1>CategoriesTree</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ categories_tree.id }}</td>
            </tr>
            <tr>
                <th>Tree_id</th>
                <td>{{ categories_tree.treeId }}</td>
            </tr>
            <tr>
                <th>Children</th>
                {# <td>{{ categories_tree.children ? categories_tree.children|join(', ') : '' }}</td> #}
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_categories_tree_index') }}">back to list</a>

    <a href="{{ path('app_categories_tree_edit', {'id': categories_tree.id}) }}">edit</a>

    {{ include('categories_tree/_delete_form.html.twig') }}
{% endblock %}